general {
    border_size = 0
    col.active_border = rgba(00000000)
    col.inactive_border = rgba(00000000)
    gaps_in = 10
    gaps_out = 20
}

decoration {
    rounding = 0
    shadow {
        range = 1
        sharp = 1
        offset = 3 3
        color = rgba(4e4b4270)
        color_inactive = rgba(00000000)
    }
}

plugin {
    hyprbars {
	bar_height = 40
	bar_text_size = 17
	bar_text_align = left

	bar_color = rgb(4e4b42)
	col.text = rgb(dad4bb)
    }
}
