general {
    border_size = 0
    col.active_border = rgba(00000000)
    col.inactive_border = rgba(00000000)
    gaps_in = 10
    gaps_out = 20
}

decoration {
    rounding = 0
    shadow {
        range = 1
        sharp = 1
        offset = 5 5
        color = rgba(b4af9aff)
        color_inactive = rgba(00000000)
    }
}